# Generated by Django 2.0.7 on 2018-08-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_and_decryption', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
    ]
